# -*- coding: utf-8 -*-
# *** Spyder Python Console History Log ***

## ---(Mon Dec  5 11:05:55 2022)---
runfile('C:/Users/LukeVidacovich/.spyder-py3/temp.py', wdir='C:/Users/LukeVidacovich/.spyder-py3')
clear
runfile('C:/Users/LukeVidacovich/.spyder-py3/temp.py', wdir='C:/Users/LukeVidacovich/.spyder-py3')
debugfile('C:/Users/LukeVidacovich/.spyder-py3/temp.py', wdir='C:/Users/LukeVidacovich/.spyder-py3')
runfile('C:/Users/LukeVidacovich/.spyder-py3/temp.py', wdir='C:/Users/LukeVidacovich/.spyder-py3')
debugfile('C:/Users/LukeVidacovich/.spyder-py3/temp.py', wdir='C:/Users/LukeVidacovich/.spyder-py3')
runfile('C:/Users/LukeVidacovich/.spyder-py3/temp.py', wdir='C:/Users/LukeVidacovich/.spyder-py3')
debugfile('C:/Users/LukeVidacovich/.spyder-py3/temp.py', wdir='C:/Users/LukeVidacovich/.spyder-py3')
runfile('C:/Users/LukeVidacovich/.spyder-py3/temp.py', wdir='C:/Users/LukeVidacovich/.spyder-py3')
debugfile('C:/Users/LukeVidacovich/.spyder-py3/temp.py', wdir='C:/Users/LukeVidacovich/.spyder-py3')
runfile('C:/Users/LukeVidacovich/.spyder-py3/temp.py', wdir='C:/Users/LukeVidacovich/.spyder-py3')
runfile('C:/Users/LukeVidacovich/.spyder-py3/AOC22_day1_part1.py', wdir='C:/Users/LukeVidacovich/.spyder-py3')
runfile('C:/Users/LukeVidacovich/.spyder-py3/AOC22_day1_part2.py', wdir='C:/Users/LukeVidacovich/.spyder-py3')
debugfile('C:/Users/LukeVidacovich/.spyder-py3/AOC22_day1_part2.py', wdir='C:/Users/LukeVidacovich/.spyder-py3')
debugfile('C:/Users/LukeVidacovich/.spyder-py3/AOC22_day2.py', wdir='C:/Users/LukeVidacovich/.spyder-py3')
runfile('C:/Users/LukeVidacovich/.spyder-py3/AOC22_day2.py', wdir='C:/Users/LukeVidacovich/.spyder-py3')
debugfile('C:/Users/LukeVidacovich/.spyder-py3/AOC22_day2.py', wdir='C:/Users/LukeVidacovich/.spyder-py3')
runfile('C:/Users/LukeVidacovich/.spyder-py3/AOC22_day2.py', wdir='C:/Users/LukeVidacovich/.spyder-py3')
runfile('C:/Users/LukeVidacovich/.spyder-py3/AOC22_day2_part2.py', wdir='C:/Users/LukeVidacovich/.spyder-py3')
runfile('C:/Users/LukeVidacovich/.spyder-py3/AOC22_day3_part1.py', wdir='C:/Users/LukeVidacovich/.spyder-py3')
debugfile('C:/Users/LukeVidacovich/.spyder-py3/AOC22_day3_part1.py', wdir='C:/Users/LukeVidacovich/.spyder-py3')
runfile('C:/Users/LukeVidacovich/.spyder-py3/AOC22_day3_part1.py', wdir='C:/Users/LukeVidacovich/.spyder-py3')
debugfile('C:/Users/LukeVidacovich/.spyder-py3/AOC22_day3_part1.py', wdir='C:/Users/LukeVidacovich/.spyder-py3')
runfile('C:/Users/LukeVidacovich/.spyder-py3/AOC22_day3_part1.py', wdir='C:/Users/LukeVidacovich/.spyder-py3')
debugfile('C:/Users/LukeVidacovich/.spyder-py3/AOC22_day3_part1.py', wdir='C:/Users/LukeVidacovich/.spyder-py3')
runfile('C:/Users/LukeVidacovich/.spyder-py3/AOC22_day3_part1.py', wdir='C:/Users/LukeVidacovich/.spyder-py3')